language: bash

sudo: required
dist: trusty

services:
- docker

env:
- QEMU_VERSION='2.6.0' REPO='alpine' TAG='latest' 
- QEMU_VERSION='2.6.0' REPO='alpine' TAG='3.7'
- QEMU_VERSION='2.6.0' REPO='alpine' TAG='3.6' 

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# Replace alpine version with travis env variable
- sed -i "s/latest/${TAG}/g" Dockerfile
# build image
- docker build -t ${DOCKER_USER}/${REPO}:${TAG} .
# test image
- docker run ${DOCKER_USER}/${REPO}:${TAG} uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    docker push ${DOCKER_USER}/${REPO}
  fi

after_script:
- "curl -X POST https://hooks.microbadger.com/images/${DOCKER_USER}/${REPO}/-QVKg7-ij2ceJ1jpMA7Zs-Z9Mig="