language: bash

sudo: required
dist: trusty

services:
- docker

env:
  - QEMU_VERSION="2.6.0" ALPINE_VERSION='latest'
  - QEMU_VERSION="2.6.0" ALPINE_VERSION='3.7'
  - QEMU_VERSION="2.6.0" ALPINE_VERSION='3.6'

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# Replace alpine version with travis env variable
- sed -i "s/latest/${ALPINE_VERSION}/g" Dockerfile
# build image
- docker build -t ckaserer/alpine:${ALPINE_VERSION} .
# test image
- docker run ckaserer/alpine:${ALPINE_VERSION} uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    docker push ckaserer/alpine
  fi