language: bash

sudo: required
dist: trusty

services:
- docker

env:
  - QEMU_VERSION="2.6.0"

script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

# get qemu-arm-static binary
- mkdir tmp
- >
  pushd tmp &&
  curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v${QEMU_VERSION}/qemu-arm-static.tar.gz &&
  tar xzf qemu-arm-static.tar.gz &&
  popd
# build image
- docker build -t ckaserer/alpine:build .
# test image
- docker run ckaserer/alpine:build uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    TAG=$(grep "FROM " Dockerfile | sed 's/.*://')
    docker tag ckaserer/alpine:build ckaserer/alpine:$TAG
    docker tag ckaserer/alpine:build ckaserer/alpine:latest
    docker push ckaserer/alpine:$TAG
    docker push ckaserer/alpine:latest
  fi
